### ISSUE TITLE
 As a commuter, I want to open the HTML file from my mobile device, so that I can quickly access train schedules on the go. #1

### ISSUE THREAD

**Issue by Joeliinus** [Joeliinus/Elroni_Telefonibrowser#1]
As a commuter, I want to open an HTML page on my mobile device, so that I can quickly access the train schedules for Tondi and Kivimäe stations on the go.

- [x] Create an HTML file that displays only the train schedules for Tondi and Kivimäe.
- [x] Ensure the HTML layout is optimized for mobile viewing.
- [x] Include the next train departure times for Tondi and Kivimäe.
- [x] Verify that the page loads quickly on both desktop and mobile devices.
- [x] Test the HTML file for compatibility across different mobile browsers.

**Comment by sandertuisk** [comment]
![image](https://github.com/user-attachments/assets/8a1f314f-ccd2-4226-823e-77c6f491b982)
