### ISSUE TITLE
As a commuter, I want a settings menu to change the background music and background color, so that I can personalize my browsing experience while viewing train schedules.

### ISSUE THREAD

**Issue by Joeliinus** [Joeliinus/Elroni_Telefonibrowser#4]
This feature provides commuters with a settings menu that allows them to customize their experience by selecting background music and adjusting the background color of the schedule view. This adds a layer of personalization, making the schedule interface more enjoyable and user-friendly.

- [x] Create a settings menu accessible from the main schedule view.
- [x] Add an option for users to select and control background music (e.g., play, pause, volume).
- [x] Add an option for users to change the browser language to english or estonian.
- [x] Provide a selection of background colors for the user to choose from, with options for light and dark themes.
- [x] Ensure that selected settings persist when the user revisits the page.
- [x] Test the functionality on mobile and desktop browsers for compatibility.
- [x] Verify that the background color and music settings do not interfere with the schedule display or readability.
- [x] Confirm that the settings menu is easy to use and accessible for all users.

**Comment by sandertuisk** [comment]
![image](https://github.com/user-attachments/assets/d21c8c0f-ea46-4eca-b1a9-5c9d7db0d691)
